/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_delimiter = 1,
  anon_sym_PERCENT_LBRACE = 2,
  aux_sym_c_code_block_token1 = 3,
  aux_sym_c_code_block_token2 = 4,
  anon_sym_PERCENT_RBRACE = 5,
  aux_sym_macro_definition_token1 = 6,
  aux_sym_macro_definition_token2 = 7,
  aux_sym_pattern_token1 = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  aux_sym_action_token1 = 11,
  aux_sym_action_token2 = 12,
  sym_user_code_section = 13,
  anon_sym_SLASH_STAR = 14,
  aux_sym_comment_token1 = 15,
  anon_sym_SLASH = 16,
  anon_sym_SLASH_SLASH = 17,
  aux_sym_comment_token2 = 18,
  sym_source_file = 19,
  sym_definitions_section = 20,
  sym_c_code_block = 21,
  sym_macro_definition = 22,
  sym_rules_section = 23,
  sym_rule = 24,
  sym_pattern = 25,
  sym_action = 26,
  sym_comment = 27,
  aux_sym_definitions_section_repeat1 = 28,
  aux_sym_c_code_block_repeat1 = 29,
  aux_sym_rules_section_repeat1 = 30,
  aux_sym_action_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_delimiter] = "delimiter",
  [anon_sym_PERCENT_LBRACE] = "%{",
  [aux_sym_c_code_block_token1] = "c_code_block_token1",
  [aux_sym_c_code_block_token2] = "c_code_block_token2",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [aux_sym_macro_definition_token1] = "macro_definition_token1",
  [aux_sym_macro_definition_token2] = "macro_definition_token2",
  [aux_sym_pattern_token1] = "pattern_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_action_token1] = "action_token1",
  [aux_sym_action_token2] = "action_token2",
  [sym_user_code_section] = "user_code_section",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH] = "/",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_source_file] = "source_file",
  [sym_definitions_section] = "definitions_section",
  [sym_c_code_block] = "c_code_block",
  [sym_macro_definition] = "macro_definition",
  [sym_rules_section] = "rules_section",
  [sym_rule] = "rule",
  [sym_pattern] = "pattern",
  [sym_action] = "action",
  [sym_comment] = "comment",
  [aux_sym_definitions_section_repeat1] = "definitions_section_repeat1",
  [aux_sym_c_code_block_repeat1] = "c_code_block_repeat1",
  [aux_sym_rules_section_repeat1] = "rules_section_repeat1",
  [aux_sym_action_repeat1] = "action_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_delimiter] = sym_delimiter,
  [anon_sym_PERCENT_LBRACE] = anon_sym_PERCENT_LBRACE,
  [aux_sym_c_code_block_token1] = aux_sym_c_code_block_token1,
  [aux_sym_c_code_block_token2] = aux_sym_c_code_block_token2,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [aux_sym_macro_definition_token1] = aux_sym_macro_definition_token1,
  [aux_sym_macro_definition_token2] = aux_sym_macro_definition_token2,
  [aux_sym_pattern_token1] = aux_sym_pattern_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_action_token1] = aux_sym_action_token1,
  [aux_sym_action_token2] = aux_sym_action_token2,
  [sym_user_code_section] = sym_user_code_section,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_source_file] = sym_source_file,
  [sym_definitions_section] = sym_definitions_section,
  [sym_c_code_block] = sym_c_code_block,
  [sym_macro_definition] = sym_macro_definition,
  [sym_rules_section] = sym_rules_section,
  [sym_rule] = sym_rule,
  [sym_pattern] = sym_pattern,
  [sym_action] = sym_action,
  [sym_comment] = sym_comment,
  [aux_sym_definitions_section_repeat1] = aux_sym_definitions_section_repeat1,
  [aux_sym_c_code_block_repeat1] = aux_sym_c_code_block_repeat1,
  [aux_sym_rules_section_repeat1] = aux_sym_rules_section_repeat1,
  [aux_sym_action_repeat1] = aux_sym_action_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_c_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_c_code_block_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_definition_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_action_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_action_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_user_code_section] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definitions_section] = {
    .visible = true,
    .named = true,
  },
  [sym_c_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_rules_section] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_definitions_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_c_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rules_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_action_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_identifier = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_identifier] = "identifier",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '%') ADVANCE(4);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '{') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '/') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(16);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(16);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '/') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(50);
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(50);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(39);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '{') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_delimiter);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_c_code_block_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_c_code_block_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_c_code_block_token1);
      if (lookahead == '/') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_c_code_block_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_macro_definition_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_macro_definition_token2);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_macro_definition_token2);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_macro_definition_token2);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_macro_definition_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_action_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_action_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_action_token1);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '{') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_action_token1);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_action_token2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_user_code_section);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_user_code_section);
      if (lookahead == '/') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_user_code_section);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_user_code_section);
      if (eof) ADVANCE(15);
      if (lookahead == '/') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(8);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(8);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 43},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 59},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {(TSStateId)(-1),},
  [45] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(1),
    [aux_sym_c_code_block_token2] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [aux_sym_macro_definition_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym_definitions_section] = STATE(33),
    [sym_c_code_block] = STATE(24),
    [sym_macro_definition] = STATE(24),
    [sym_comment] = STATE(1),
    [aux_sym_definitions_section_repeat1] = STATE(6),
    [sym_delimiter] = ACTIONS(7),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(9),
    [aux_sym_macro_definition_token1] = ACTIONS(11),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH_SLASH] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_delimiter,
    ACTIONS(17), 1,
      aux_sym_pattern_token1,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(2), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_rules_section_repeat1,
    STATE(10), 1,
      sym_rule,
    STATE(21), 1,
      sym_pattern,
    STATE(31), 1,
      sym_rules_section,
  [34] = 11,
    ACTIONS(17), 1,
      aux_sym_pattern_token1,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_delimiter,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_rules_section_repeat1,
    STATE(10), 1,
      sym_rule,
    STATE(21), 1,
      sym_pattern,
    STATE(30), 1,
      sym_rules_section,
  [68] = 10,
    ACTIONS(17), 1,
      aux_sym_pattern_token1,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_delimiter,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_rules_section_repeat1,
    STATE(10), 1,
      sym_rule,
    STATE(21), 1,
      sym_pattern,
  [99] = 9,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_delimiter,
    ACTIONS(37), 1,
      aux_sym_pattern_token1,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_rule,
    STATE(21), 1,
      sym_pattern,
    STATE(5), 2,
      sym_comment,
      aux_sym_rules_section_repeat1,
  [128] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LBRACE,
    ACTIONS(11), 1,
      aux_sym_macro_definition_token1,
    ACTIONS(43), 1,
      sym_delimiter,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_definitions_section_repeat1,
    STATE(24), 2,
      sym_c_code_block,
      sym_macro_definition,
  [154] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      sym_delimiter,
    ACTIONS(47), 1,
      anon_sym_PERCENT_LBRACE,
    ACTIONS(50), 1,
      aux_sym_macro_definition_token1,
    STATE(7), 2,
      sym_comment,
      aux_sym_definitions_section_repeat1,
    STATE(24), 2,
      sym_c_code_block,
      sym_macro_definition,
  [178] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(53), 2,
      aux_sym_c_code_block_token1,
      aux_sym_c_code_block_token2,
    STATE(8), 2,
      sym_comment,
      aux_sym_c_code_block_repeat1,
  [196] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 2,
      aux_sym_action_token1,
      aux_sym_action_token2,
    STATE(9), 2,
      sym_comment,
      aux_sym_action_repeat1,
  [214] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(65), 2,
      sym_delimiter,
      aux_sym_pattern_token1,
  [232] = 6,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_action_repeat1,
    ACTIONS(69), 2,
      aux_sym_action_token1,
      aux_sym_action_token2,
  [252] = 6,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(73), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_c_code_block_repeat1,
    ACTIONS(71), 2,
      aux_sym_c_code_block_token1,
      aux_sym_c_code_block_token2,
  [272] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(77), 2,
      sym_delimiter,
      aux_sym_pattern_token1,
  [290] = 6,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(79), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(8), 1,
      aux_sym_c_code_block_repeat1,
    STATE(14), 1,
      sym_comment,
    ACTIONS(71), 2,
      aux_sym_c_code_block_token1,
      aux_sym_c_code_block_token2,
  [310] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(83), 2,
      sym_delimiter,
      aux_sym_pattern_token1,
  [328] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(87), 2,
      sym_delimiter,
      aux_sym_pattern_token1,
  [346] = 6,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      aux_sym_action_repeat1,
    STATE(17), 1,
      sym_comment,
    ACTIONS(69), 2,
      aux_sym_action_token1,
      aux_sym_action_token2,
  [366] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(93), 2,
      sym_delimiter,
      aux_sym_pattern_token1,
  [384] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(95), 3,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_macro_definition_token1,
  [399] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(97), 3,
      aux_sym_c_code_block_token1,
      aux_sym_c_code_block_token2,
      anon_sym_PERCENT_RBRACE,
  [414] = 6,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(99), 1,
      aux_sym_macro_definition_token2,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_action,
    STATE(21), 1,
      sym_comment,
  [433] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(103), 3,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_macro_definition_token1,
  [448] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(105), 3,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_macro_definition_token1,
  [463] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(107), 3,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_macro_definition_token1,
  [478] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_RBRACE,
      aux_sym_action_token1,
      aux_sym_action_token2,
  [493] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(111), 2,
      aux_sym_macro_definition_token2,
      anon_sym_LBRACE,
  [507] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 1,
      sym_user_code_section,
    STATE(27), 1,
      sym_comment,
  [523] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(117), 2,
      aux_sym_macro_definition_token2,
      anon_sym_LBRACE,
  [537] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 1,
      sym_user_code_section,
    STATE(29), 1,
      sym_comment,
  [553] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 1,
      sym_delimiter,
    STATE(30), 1,
      sym_comment,
  [569] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 1,
      sym_delimiter,
    STATE(31), 1,
      sym_comment,
  [585] = 5,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 1,
      sym_user_code_section,
    STATE(32), 1,
      sym_comment,
  [601] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(129), 1,
      sym_delimiter,
    STATE(33), 1,
      sym_comment,
  [614] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(131), 1,
      aux_sym_comment_token2,
    STATE(34), 1,
      sym_comment,
  [627] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(133), 1,
      aux_sym_comment_token1,
    STATE(35), 1,
      sym_comment,
  [640] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    STATE(36), 1,
      sym_comment,
  [653] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_comment,
  [666] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(139), 1,
      aux_sym_macro_definition_token1,
    STATE(38), 1,
      sym_comment,
  [679] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_comment,
  [692] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(141), 1,
      anon_sym_SLASH,
    STATE(40), 1,
      sym_comment,
  [705] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(143), 1,
      aux_sym_macro_definition_token2,
    STATE(41), 1,
      sym_comment,
  [718] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      sym_comment,
  [731] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    STATE(43), 1,
      sym_comment,
  [744] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [748] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 178,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 232,
  [SMALL_STATE(12)] = 252,
  [SMALL_STATE(13)] = 272,
  [SMALL_STATE(14)] = 290,
  [SMALL_STATE(15)] = 310,
  [SMALL_STATE(16)] = 328,
  [SMALL_STATE(17)] = 346,
  [SMALL_STATE(18)] = 366,
  [SMALL_STATE(19)] = 384,
  [SMALL_STATE(20)] = 399,
  [SMALL_STATE(21)] = 414,
  [SMALL_STATE(22)] = 433,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 463,
  [SMALL_STATE(25)] = 478,
  [SMALL_STATE(26)] = 493,
  [SMALL_STATE(27)] = 507,
  [SMALL_STATE(28)] = 523,
  [SMALL_STATE(29)] = 537,
  [SMALL_STATE(30)] = 553,
  [SMALL_STATE(31)] = 569,
  [SMALL_STATE(32)] = 585,
  [SMALL_STATE(33)] = 601,
  [SMALL_STATE(34)] = 614,
  [SMALL_STATE(35)] = 627,
  [SMALL_STATE(36)] = 640,
  [SMALL_STATE(37)] = 653,
  [SMALL_STATE(38)] = 666,
  [SMALL_STATE(39)] = 679,
  [SMALL_STATE(40)] = 692,
  [SMALL_STATE(41)] = 705,
  [SMALL_STATE(42)] = 718,
  [SMALL_STATE(43)] = 731,
  [SMALL_STATE(44)] = 744,
  [SMALL_STATE(45)] = 748,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_section, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rules_section, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definitions_section, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_c_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_c_code_block_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rules_section_repeat1, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_c_code_block, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_c_code_block_repeat1, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 2, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_c_code_block, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
