/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_delimiter = 1,
  anon_sym_PERCENT_LBRACE = 2,
  aux_sym_c_code_block_token1 = 3,
  anon_sym_PERCENT_RBRACE = 4,
  aux_sym_option_definition_token1 = 5,
  aux_sym_option_definition_token2 = 6,
  aux_sym_macro_name_token1 = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_pattern_token1 = 9,
  aux_sym_pattern_token2 = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  aux_sym_braced_action_token1 = 13,
  aux_sym_braced_action_token2 = 14,
  sym_user_code_section = 15,
  sym_newline = 16,
  sym_source_file = 17,
  sym_definitions_section = 18,
  sym_c_code_block = 19,
  sym_option_definition = 20,
  sym_macro_definition = 21,
  sym_macro_name = 22,
  sym_macro_value = 23,
  sym_rules_section = 24,
  sym_rule = 25,
  sym_pattern = 26,
  sym_action = 27,
  sym_braced_action = 28,
  sym_inline_action = 29,
  aux_sym_definitions_section_repeat1 = 30,
  aux_sym_c_code_block_repeat1 = 31,
  aux_sym_rules_section_repeat1 = 32,
  aux_sym_pattern_repeat1 = 33,
  aux_sym_braced_action_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_delimiter] = "delimiter",
  [anon_sym_PERCENT_LBRACE] = "%{",
  [aux_sym_c_code_block_token1] = "c_code_block_token1",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [aux_sym_option_definition_token1] = "option_definition_token1",
  [aux_sym_option_definition_token2] = "option_definition_token2",
  [aux_sym_macro_name_token1] = "macro_name_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_pattern_token1] = "pattern_token1",
  [aux_sym_pattern_token2] = "pattern_token2",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_braced_action_token1] = "braced_action_token1",
  [aux_sym_braced_action_token2] = "braced_action_token2",
  [sym_user_code_section] = "user_code_section",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_definitions_section] = "definitions_section",
  [sym_c_code_block] = "c_code_block",
  [sym_option_definition] = "option_definition",
  [sym_macro_definition] = "macro_definition",
  [sym_macro_name] = "macro_name",
  [sym_macro_value] = "macro_value",
  [sym_rules_section] = "rules_section",
  [sym_rule] = "rule",
  [sym_pattern] = "pattern",
  [sym_action] = "action",
  [sym_braced_action] = "braced_action",
  [sym_inline_action] = "inline_action",
  [aux_sym_definitions_section_repeat1] = "definitions_section_repeat1",
  [aux_sym_c_code_block_repeat1] = "c_code_block_repeat1",
  [aux_sym_rules_section_repeat1] = "rules_section_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_braced_action_repeat1] = "braced_action_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_delimiter] = sym_delimiter,
  [anon_sym_PERCENT_LBRACE] = anon_sym_PERCENT_LBRACE,
  [aux_sym_c_code_block_token1] = aux_sym_c_code_block_token1,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [aux_sym_option_definition_token1] = aux_sym_option_definition_token1,
  [aux_sym_option_definition_token2] = aux_sym_option_definition_token2,
  [aux_sym_macro_name_token1] = aux_sym_macro_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_pattern_token1] = aux_sym_pattern_token1,
  [aux_sym_pattern_token2] = aux_sym_pattern_token2,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_braced_action_token1] = aux_sym_braced_action_token1,
  [aux_sym_braced_action_token2] = aux_sym_braced_action_token2,
  [sym_user_code_section] = sym_user_code_section,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_definitions_section] = sym_definitions_section,
  [sym_c_code_block] = sym_c_code_block,
  [sym_option_definition] = sym_option_definition,
  [sym_macro_definition] = sym_macro_definition,
  [sym_macro_name] = sym_macro_name,
  [sym_macro_value] = sym_macro_value,
  [sym_rules_section] = sym_rules_section,
  [sym_rule] = sym_rule,
  [sym_pattern] = sym_pattern,
  [sym_action] = sym_action,
  [sym_braced_action] = sym_braced_action,
  [sym_inline_action] = sym_inline_action,
  [aux_sym_definitions_section_repeat1] = aux_sym_definitions_section_repeat1,
  [aux_sym_c_code_block_repeat1] = aux_sym_c_code_block_repeat1,
  [aux_sym_rules_section_repeat1] = aux_sym_rules_section_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_braced_action_repeat1] = aux_sym_braced_action_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_c_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_option_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_definition_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_pattern_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_braced_action_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_action_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_user_code_section] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definitions_section] = {
    .visible = true,
    .named = true,
  },
  [sym_c_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_option_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_value] = {
    .visible = true,
    .named = true,
  },
  [sym_rules_section] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_action] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_action] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_definitions_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_c_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rules_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_action_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '%') ADVANCE(6);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(38);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_c_code_block_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_option_definition_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_option_definition_token2);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_option_definition_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_option_definition_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_macro_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_pattern_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_pattern_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '/' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_braced_action_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_braced_action_token1);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_braced_action_token1);
      if (lookahead == '}') ADVANCE(38);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_braced_action_token2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_user_code_section);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_user_code_section);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_user_code_section);
      if (eof) ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 41},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 41},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 41},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [aux_sym_option_definition_token1] = ACTIONS(1),
    [aux_sym_macro_name_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym_definitions_section] = STATE(43),
    [sym_c_code_block] = STATE(3),
    [sym_option_definition] = STATE(3),
    [sym_macro_definition] = STATE(3),
    [sym_macro_name] = STATE(32),
    [aux_sym_definitions_section_repeat1] = STATE(3),
    [sym_delimiter] = ACTIONS(3),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(5),
    [aux_sym_option_definition_token1] = ACTIONS(7),
    [aux_sym_macro_name_token1] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_delimiter,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_pattern_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_newline,
    STATE(13), 1,
      sym_pattern,
    STATE(29), 1,
      sym_rules_section,
    STATE(7), 2,
      sym_rule,
      aux_sym_rules_section_repeat1,
  [29] = 7,
    ACTIONS(5), 1,
      anon_sym_PERCENT_LBRACE,
    ACTIONS(7), 1,
      aux_sym_option_definition_token1,
    ACTIONS(9), 1,
      aux_sym_macro_name_token1,
    ACTIONS(25), 1,
      sym_delimiter,
    ACTIONS(27), 1,
      sym_newline,
    STATE(32), 1,
      sym_macro_name,
    STATE(5), 4,
      sym_c_code_block,
      sym_option_definition,
      sym_macro_definition,
      aux_sym_definitions_section_repeat1,
  [54] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_pattern_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_newline,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_delimiter,
    STATE(13), 1,
      sym_pattern,
    STATE(25), 1,
      sym_rules_section,
    STATE(7), 2,
      sym_rule,
      aux_sym_rules_section_repeat1,
  [83] = 7,
    ACTIONS(33), 1,
      sym_delimiter,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LBRACE,
    ACTIONS(38), 1,
      aux_sym_option_definition_token1,
    ACTIONS(41), 1,
      aux_sym_macro_name_token1,
    ACTIONS(44), 1,
      sym_newline,
    STATE(32), 1,
      sym_macro_name,
    STATE(5), 4,
      sym_c_code_block,
      sym_option_definition,
      sym_macro_definition,
      aux_sym_definitions_section_repeat1,
  [108] = 7,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      aux_sym_pattern_token2,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(58), 1,
      sym_newline,
    STATE(13), 1,
      sym_pattern,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_delimiter,
    STATE(6), 2,
      sym_rule,
      aux_sym_rules_section_repeat1,
  [132] = 7,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_pattern_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_newline,
    STATE(13), 1,
      sym_pattern,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_delimiter,
    STATE(6), 2,
      sym_rule,
      aux_sym_rules_section_repeat1,
  [156] = 1,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      sym_delimiter,
      anon_sym_DQUOTE,
      aux_sym_pattern_token2,
      anon_sym_LBRACE,
      sym_newline,
  [165] = 1,
    ACTIONS(67), 5,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_option_definition_token1,
      aux_sym_macro_name_token1,
      sym_newline,
  [173] = 1,
    ACTIONS(69), 5,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_option_definition_token1,
      aux_sym_macro_name_token1,
      sym_newline,
  [181] = 1,
    ACTIONS(71), 5,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_option_definition_token1,
      aux_sym_macro_name_token1,
      sym_newline,
  [189] = 1,
    ACTIONS(73), 5,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_option_definition_token1,
      aux_sym_macro_name_token1,
      sym_newline,
  [197] = 4,
    ACTIONS(75), 1,
      aux_sym_option_definition_token2,
    ACTIONS(77), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_action,
    STATE(39), 2,
      sym_braced_action,
      sym_inline_action,
  [211] = 1,
    ACTIONS(79), 5,
      sym_delimiter,
      anon_sym_PERCENT_LBRACE,
      aux_sym_option_definition_token1,
      aux_sym_macro_name_token1,
      sym_newline,
  [219] = 3,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_braced_action_repeat1,
    ACTIONS(83), 2,
      aux_sym_braced_action_token1,
      aux_sym_braced_action_token2,
  [230] = 3,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_braced_action_repeat1,
    ACTIONS(87), 2,
      aux_sym_braced_action_token1,
      aux_sym_braced_action_token2,
  [241] = 3,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_braced_action_repeat1,
    ACTIONS(92), 2,
      aux_sym_braced_action_token1,
      aux_sym_braced_action_token2,
  [252] = 3,
    ACTIONS(94), 1,
      anon_sym_DQUOTE,
    ACTIONS(96), 1,
      aux_sym_pattern_token1,
    STATE(18), 1,
      aux_sym_pattern_repeat1,
  [262] = 3,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    ACTIONS(101), 1,
      aux_sym_pattern_token1,
    STATE(20), 1,
      aux_sym_pattern_repeat1,
  [272] = 3,
    ACTIONS(103), 1,
      anon_sym_DQUOTE,
    ACTIONS(105), 1,
      aux_sym_pattern_token1,
    STATE(18), 1,
      aux_sym_pattern_repeat1,
  [282] = 3,
    ACTIONS(107), 1,
      aux_sym_c_code_block_token1,
    ACTIONS(109), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(23), 1,
      aux_sym_c_code_block_repeat1,
  [292] = 3,
    ACTIONS(111), 1,
      aux_sym_c_code_block_token1,
    ACTIONS(114), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(22), 1,
      aux_sym_c_code_block_repeat1,
  [302] = 3,
    ACTIONS(116), 1,
      aux_sym_c_code_block_token1,
    ACTIONS(118), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(22), 1,
      aux_sym_c_code_block_repeat1,
  [312] = 2,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      sym_user_code_section,
  [319] = 2,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_delimiter,
  [326] = 1,
    ACTIONS(122), 2,
      aux_sym_option_definition_token2,
      anon_sym_LBRACE,
  [331] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      sym_user_code_section,
  [338] = 1,
    ACTIONS(128), 2,
      aux_sym_option_definition_token2,
      anon_sym_LBRACE,
  [343] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 1,
      sym_delimiter,
  [350] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 1,
      sym_user_code_section,
  [357] = 1,
    ACTIONS(136), 2,
      aux_sym_option_definition_token2,
      anon_sym_LBRACE,
  [362] = 2,
    ACTIONS(138), 1,
      aux_sym_option_definition_token2,
    STATE(12), 1,
      sym_macro_value,
  [369] = 1,
    ACTIONS(140), 1,
      aux_sym_option_definition_token2,
  [373] = 1,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
  [377] = 1,
    ACTIONS(144), 1,
      aux_sym_macro_name_token1,
  [381] = 1,
    ACTIONS(146), 1,
      sym_newline,
  [385] = 1,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [389] = 1,
    ACTIONS(148), 1,
      sym_newline,
  [393] = 1,
    ACTIONS(150), 1,
      sym_newline,
  [397] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [401] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [405] = 1,
    ACTIONS(154), 1,
      sym_newline,
  [409] = 1,
    ACTIONS(156), 1,
      sym_delimiter,
  [413] = 1,
    ACTIONS(158), 1,
      sym_newline,
  [417] = 1,
    ACTIONS(160), 1,
      aux_sym_option_definition_token2,
  [421] = 1,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 83,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 165,
  [SMALL_STATE(10)] = 173,
  [SMALL_STATE(11)] = 181,
  [SMALL_STATE(12)] = 189,
  [SMALL_STATE(13)] = 197,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 219,
  [SMALL_STATE(16)] = 230,
  [SMALL_STATE(17)] = 241,
  [SMALL_STATE(18)] = 252,
  [SMALL_STATE(19)] = 262,
  [SMALL_STATE(20)] = 272,
  [SMALL_STATE(21)] = 282,
  [SMALL_STATE(22)] = 292,
  [SMALL_STATE(23)] = 302,
  [SMALL_STATE(24)] = 312,
  [SMALL_STATE(25)] = 319,
  [SMALL_STATE(26)] = 326,
  [SMALL_STATE(27)] = 331,
  [SMALL_STATE(28)] = 338,
  [SMALL_STATE(29)] = 343,
  [SMALL_STATE(30)] = 350,
  [SMALL_STATE(31)] = 357,
  [SMALL_STATE(32)] = 362,
  [SMALL_STATE(33)] = 369,
  [SMALL_STATE(34)] = 373,
  [SMALL_STATE(35)] = 377,
  [SMALL_STATE(36)] = 381,
  [SMALL_STATE(37)] = 385,
  [SMALL_STATE(38)] = 389,
  [SMALL_STATE(39)] = 393,
  [SMALL_STATE(40)] = 397,
  [SMALL_STATE(41)] = 401,
  [SMALL_STATE(42)] = 405,
  [SMALL_STATE(43)] = 409,
  [SMALL_STATE(44)] = 413,
  [SMALL_STATE(45)] = 417,
  [SMALL_STATE(46)] = 421,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definitions_section, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definitions_section_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rules_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_section, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_c_code_block, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_c_code_block, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_value, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_definition, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_braced_action_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_action_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_c_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_c_code_block_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_action, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_action, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_action, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_name, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
